version: '3.1'

services:
  flowise:
    image: flowiseai/flowise
    restart: always
    container_name: flowise
    environment:
      - PORT=${FLOWISE_PORT}
      - CORS_ORIGINS=${CORS_ORIGINS}
      - IFRAME_ORIGINS=${IFRAME_ORIGINS}
      - FLOWISE_USERNAME=${FLOWISE_USERNAME}
      - FLOWISE_PASSWORD=${FLOWISE_PASSWORD}
      - FLOWISE_FILE_SIZE_LIMIT=${FLOWISE_FILE_SIZE_LIMIT}
      - DEBUG=${DEBUG}
      - DATABASE_PATH=${DATABASE_PATH}
      - DATABASE_TYPE=${DATABASE_TYPE}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
      - DATABASE_SSL_KEY_BASE64=${DATABASE_SSL_KEY_BASE64}
      - APIKEY_PATH=${APIKEY_PATH}
      - SECRETKEY_PATH=${SECRETKEY_PATH}
      - FLOWISE_SECRETKEY_OVERWRITE=${FLOWISE_SECRETKEY_OVERWRITE}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_PATH=${LOG_PATH}
      - BLOB_STORAGE_PATH=${BLOB_STORAGE_PATH}
      - DISABLE_FLOWISE_TELEMETRY=${DISABLE_FLOWISE_TELEMETRY}
      - MODEL_LIST_CONFIG_JSON=${MODEL_LIST_CONFIG_JSON}
    ports:
      - '${FLOWISE_PORT}:${FLOWISE_PORT}'
    volumes:
      - .flowise:/root/.flowise
      - pdf_store:/root/.flowise/pdf_store
    command: /bin/sh -c "sleep 3; flowise start"

  ollama-embed:
    image: ollama/ollama:latest
    container_name: ollama-embed
    volumes:
      - .ollama-embed:/root/.ollama
    ports:
      - '11434:11434'
    tty: true

  ollama-generation:
    image: ollama/ollama:latest
    container_name: ollama-generation
    volumes:
      - .ollama-generation:/root/.ollama
    ports:
      - '11435:11434'
    tty: true

  # ollama:
  #     image: ollama/ollama:latest
  #     container_name: ollama
  #     volumes:
  #       - .ollama:/root/.ollama
  #     ports:
  #       - '11434:11434'
  #     tty: true

volumes:
  .flowise:
  .ollama-embed:
  .ollama-generation:
  pdf_store:
